// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module MSHR(
  input         clock,
                reset,
                io_allocate_valid,
                io_allocate_bits_prio_0,
                io_allocate_bits_prio_1,
                io_allocate_bits_prio_2,
                io_allocate_bits_control,
  input  [2:0]  io_allocate_bits_opcode,
                io_allocate_bits_param,
                io_allocate_bits_size,
  input  [4:0]  io_allocate_bits_source,
  input  [11:0] io_allocate_bits_tag,
  input  [5:0]  io_allocate_bits_offset,
                io_allocate_bits_put,
  input  [9:0]  io_allocate_bits_set,
  input         io_allocate_bits_repeat,
                io_directory_valid,
                io_directory_bits_dirty,
  input  [1:0]  io_directory_bits_state,
  input         io_directory_bits_clients,
  input  [11:0] io_directory_bits_tag,
  input         io_directory_bits_hit,
  input  [2:0]  io_directory_bits_way,
  input         io_schedule_ready,
                io_sinkc_valid,
                io_sinkc_bits_last,
  input  [11:0] io_sinkc_bits_tag,
  input  [4:0]  io_sinkc_bits_source,
  input  [2:0]  io_sinkc_bits_param,
  input         io_sinkc_bits_data,
                io_sinkd_valid,
                io_sinkd_bits_last,
  input  [2:0]  io_sinkd_bits_opcode,
                io_sinkd_bits_param,
                io_sinkd_bits_sink,
  input         io_sinkd_bits_denied,
                io_sinke_valid,
  input  [9:0]  io_nestedwb_set,
  input  [11:0] io_nestedwb_tag,
  input         io_nestedwb_b_toN,
                io_nestedwb_b_toB,
                io_nestedwb_b_clr_dirty,
                io_nestedwb_c_set_dirty,
  output        io_status_valid,
  output [9:0]  io_status_bits_set,
  output [11:0] io_status_bits_tag,
  output [2:0]  io_status_bits_way,
  output        io_status_bits_blockC,
                io_status_bits_nestC,
                io_schedule_valid,
                io_schedule_bits_a_valid,
  output [11:0] io_schedule_bits_a_bits_tag,
  output [9:0]  io_schedule_bits_a_bits_set,
  output [2:0]  io_schedule_bits_a_bits_param,
  output        io_schedule_bits_a_bits_block,
                io_schedule_bits_b_valid,
  output [2:0]  io_schedule_bits_b_bits_param,
  output [11:0] io_schedule_bits_b_bits_tag,
  output [9:0]  io_schedule_bits_b_bits_set,
  output        io_schedule_bits_b_bits_clients,
                io_schedule_bits_b_bits_hit,
                io_schedule_bits_c_valid,
  output [2:0]  io_schedule_bits_c_bits_opcode,
                io_schedule_bits_c_bits_param,
  output [11:0] io_schedule_bits_c_bits_tag,
  output [9:0]  io_schedule_bits_c_bits_set,
  output [2:0]  io_schedule_bits_c_bits_way,
  output        io_schedule_bits_c_bits_dirty,
                io_schedule_bits_d_valid,
                io_schedule_bits_d_bits_prio_0,
                io_schedule_bits_d_bits_prio_2,
  output [2:0]  io_schedule_bits_d_bits_opcode,
                io_schedule_bits_d_bits_param,
                io_schedule_bits_d_bits_size,
  output [4:0]  io_schedule_bits_d_bits_source,
  output [5:0]  io_schedule_bits_d_bits_offset,
                io_schedule_bits_d_bits_put,
  output [9:0]  io_schedule_bits_d_bits_set,
  output [2:0]  io_schedule_bits_d_bits_way,
  output        io_schedule_bits_d_bits_bad,
                io_schedule_bits_d_bits_hit,
                io_schedule_bits_e_valid,
  output [2:0]  io_schedule_bits_e_bits_sink,
  output        io_schedule_bits_x_valid,
                io_schedule_bits_dir_valid,
  output [9:0]  io_schedule_bits_dir_bits_set,
  output [2:0]  io_schedule_bits_dir_bits_way,
  output        io_schedule_bits_dir_bits_data_dirty,
  output [1:0]  io_schedule_bits_dir_bits_data_state,
  output        io_schedule_bits_dir_bits_data_clients,
  output [11:0] io_schedule_bits_dir_bits_data_tag,
  output        io_schedule_bits_reload
);

  reg         request_valid;	// @[MSHR.scala:99:30]
  reg         request_prio_0;	// @[MSHR.scala:100:20]
  reg         request_prio_1;	// @[MSHR.scala:100:20]
  reg         request_prio_2;	// @[MSHR.scala:100:20]
  reg         request_control;	// @[MSHR.scala:100:20]
  reg  [2:0]  request_opcode;	// @[MSHR.scala:100:20]
  reg  [2:0]  request_param;	// @[MSHR.scala:100:20]
  reg  [2:0]  request_size;	// @[MSHR.scala:100:20]
  reg  [4:0]  request_source;	// @[MSHR.scala:100:20]
  reg  [11:0] request_tag;	// @[MSHR.scala:100:20]
  reg  [5:0]  request_offset;	// @[MSHR.scala:100:20]
  reg  [5:0]  request_put;	// @[MSHR.scala:100:20]
  reg  [9:0]  request_set;	// @[MSHR.scala:100:20]
  reg         meta_valid;	// @[MSHR.scala:101:27]
  reg         meta_dirty;	// @[MSHR.scala:102:17]
  reg  [1:0]  meta_state;	// @[MSHR.scala:102:17]
  reg         meta_clients;	// @[MSHR.scala:102:17]
  reg  [11:0] meta_tag;	// @[MSHR.scala:102:17]
  reg         meta_hit;	// @[MSHR.scala:102:17]
  reg  [2:0]  meta_way;	// @[MSHR.scala:102:17]
  reg         s_rprobe;	// @[MSHR.scala:123:33]
  reg         w_rprobeackfirst;	// @[MSHR.scala:124:33]
  reg         w_rprobeacklast;	// @[MSHR.scala:125:33]
  reg         s_release;	// @[MSHR.scala:126:33]
  reg         w_releaseack;	// @[MSHR.scala:127:33]
  reg         s_pprobe;	// @[MSHR.scala:128:33]
  reg         s_acquire;	// @[MSHR.scala:129:33]
  reg         s_flush;	// @[MSHR.scala:130:33]
  reg         w_grantfirst;	// @[MSHR.scala:131:33]
  reg         w_grantlast;	// @[MSHR.scala:132:33]
  reg         w_grant;	// @[MSHR.scala:133:33]
  reg         w_pprobeackfirst;	// @[MSHR.scala:134:33]
  reg         w_pprobeacklast;	// @[MSHR.scala:135:33]
  reg         w_pprobeack;	// @[MSHR.scala:136:33]
  reg         s_grantack;	// @[MSHR.scala:138:33]
  reg         s_execute;	// @[MSHR.scala:139:33]
  reg         w_grantack;	// @[MSHR.scala:140:33]
  reg         s_writeback;	// @[MSHR.scala:141:33]
  reg  [2:0]  sink;	// @[MSHR.scala:149:17]
  reg         gotT;	// @[MSHR.scala:150:17]
  reg         bad_grant;	// @[MSHR.scala:151:22]
  reg         probes_done;	// @[MSHR.scala:152:24]
  reg         probes_toN;	// @[MSHR.scala:153:23]
  wire        _io_status_bits_nestC_output = meta_valid & (~w_rprobeackfirst | ~w_pprobeackfirst | ~w_grantfirst);	// @[MSHR.scala:101:27, :124:33, :131:33, :134:33, :170:103, :175:{39,43,64,82}]
  wire        no_wait = w_rprobeacklast & w_releaseack & w_grantlast & w_pprobeacklast & w_grantack;	// @[MSHR.scala:125:33, :127:33, :132:33, :135:33, :140:33, :185:83]
  wire        _io_schedule_bits_a_valid_output = ~s_acquire & s_release & s_pprobe;	// @[MSHR.scala:126:33, :128:33, :129:33, :186:{31,55}]
  wire        _io_schedule_bits_b_valid_output = ~s_rprobe | ~s_pprobe;	// @[MSHR.scala:123:33, :128:33, :187:{31,41,44}]
  wire        _io_schedule_bits_c_valid_output = ~s_release & w_rprobeackfirst;	// @[MSHR.scala:124:33, :126:33, :188:{32,43}]
  wire        _io_schedule_bits_d_valid_output = ~s_execute & w_pprobeack & w_grant;	// @[MSHR.scala:133:33, :136:33, :139:33, :189:{31,57}]
  wire        _io_schedule_bits_e_valid_output = ~s_grantack & w_grantfirst;	// @[MSHR.scala:131:33, :138:33, :190:{31,43}]
  wire        _io_schedule_bits_x_valid_output = ~s_flush & w_releaseack;	// @[MSHR.scala:127:33, :130:33, :191:{31,40}]
  wire        _io_schedule_bits_dir_valid_output = ~s_release & w_rprobeackfirst | ~s_writeback & no_wait;	// @[MSHR.scala:124:33, :126:33, :141:33, :185:83, :188:32, :192:{45,66,70,83}]
  wire        _io_schedule_valid_output = _io_schedule_bits_a_valid_output | _io_schedule_bits_b_valid_output | _io_schedule_bits_c_valid_output | _io_schedule_bits_d_valid_output | _io_schedule_bits_e_valid_output | _io_schedule_bits_x_valid_output | _io_schedule_bits_dir_valid_output;	// @[MSHR.scala:186:55, :187:41, :188:43, :189:57, :190:43, :191:40, :192:66, :195:105]
  wire        req_clientBit = request_source == 5'h10;	// @[MSHR.scala:100:20, Parameters.scala:46:9]
  wire        _excluded_client_T_1 = request_opcode == 3'h6;	// @[MSHR.scala:100:20, Parameters.scala:270:14]
  wire        req_needT = ~(request_opcode[2]) | request_opcode == 3'h5 & request_param == 3'h1 | (_excluded_client_T_1 | (&request_opcode)) & (|request_param);	// @[MSHR.scala:100:20, Parameters.scala:268:{5,12}, :269:{13,33,42,70}, :270:{14,42,52,80,89}, :281:11]
  wire        req_acquire = _excluded_client_T_1 | (&request_opcode);	// @[MSHR.scala:100:20, :229:53, Parameters.scala:270:{14,52}]
  wire        _final_meta_writeback_state_T_2 = request_param != 3'h3 & meta_state == 2'h2;	// @[MSHR.scala:100:20, :102:17, :113:22, :235:{55,64,78}]
  wire        _final_meta_writeback_clients_T_7 = meta_clients & ~((request_param == 3'h1 | request_param == 3'h2 | request_param == 3'h5) & req_clientBit);	// @[MSHR.scala:100:20, :102:17, :236:{50,52,56}, Parameters.scala:46:9, :269:13, :281:{11,43,66,75}]
  wire        _GEN = (~meta_hit | ~probes_toN) & meta_clients;	// @[MSHR.scala:102:17, :153:23, :225:38, :239:21, :240:36, :242:{36,54}]
  wire [1:0]  _final_meta_writeback_state_T_6 = {1'h1, ~req_acquire};	// @[MSHR.scala:107:14, :229:53, :248:40]
  wire [1:0]  _final_meta_writeback_state_T_9 = {1'h1, ~(~meta_clients & req_acquire)};	// @[MSHR.scala:102:17, :107:14, :229:53, :230:25, :254:{55,72}]
  wire [1:0]  _final_meta_writeback_state_T_13 = {meta_state == 2'h2, 1'h1};	// @[MSHR.scala:102:17, :107:14, :113:22, Mux.scala:81:{58,61}]
  wire        _final_meta_writeback_clients_T_14 = meta_hit & meta_clients & ~probes_toN | req_acquire & req_clientBit;	// @[MSHR.scala:102:17, :153:23, :229:53, :255:{40,66,84}, :256:40, Parameters.scala:46:9]
  wire        _GEN_0 = request_prio_2 | request_control;	// @[MSHR.scala:100:20, :225:38, :233:52, :238:53, :257:30]
  wire        _GEN_1 = request_prio_2 | ~request_control;	// @[MSHR.scala:100:20, :233:52, :237:34, :238:53, :244:30, :258:30]
  wire        _io_schedule_bits_dir_bits_data_WIRE_dirty = ~bad_grant & (request_prio_2 ? meta_dirty | request_opcode[0] : request_control ? ~meta_hit & meta_dirty : meta_hit & meta_dirty | ~(request_opcode[2]));	// @[MSHR.scala:100:20, :102:17, :151:22, :225:38, :233:52, :234:{34,48,65}, :238:53, :239:21, :240:36, :246:{32,45,60,63}, :261:20, :262:21, Parameters.scala:268:12]
  wire [1:0]  _GEN_2 = {1'h0, meta_hit};	// @[MSHR.scala:99:30, :102:17, :262:21, :267:36, :273:36]
  wire [1:0]  _io_schedule_bits_dir_bits_data_WIRE_state = bad_grant ? _GEN_2 : request_prio_2 ? (_final_meta_writeback_state_T_2 ? 2'h3 : meta_state) : request_control ? (meta_hit ? 2'h0 : meta_state) : req_needT ? _final_meta_writeback_state_T_6 : meta_hit ? ((&meta_state) ? _final_meta_writeback_state_T_9 : _final_meta_writeback_state_T_13) : gotT ? _final_meta_writeback_state_T_6 : 2'h1;	// @[MSHR.scala:100:20, :102:17, :106:22, :110:22, :117:22, :150:17, :151:22, :225:38, :231:81, :233:52, :235:{34,40,64}, :238:53, :239:21, :241:36, :247:{32,38}, :248:40, :249:{40,55}, :254:55, :261:20, :262:21, :267:36, :273:36, Mux.scala:81:58, Parameters.scala:269:70]
  wire        _GEN_3 = meta_hit & meta_clients & ~probes_toN;	// @[MSHR.scala:102:17, :153:23, :262:21, :268:{36,54}, :274:36]
  wire        _io_schedule_bits_dir_bits_data_WIRE_clients = bad_grant ? _GEN_3 : request_prio_2 ? _final_meta_writeback_clients_T_7 : request_control ? _GEN : _final_meta_writeback_clients_T_14;	// @[MSHR.scala:100:20, :151:22, :225:38, :233:52, :236:{34,50}, :238:53, :239:21, :242:36, :255:{34,84}, :261:20, :262:21, :268:36, :274:36]
  wire        excluded_client = meta_hit & request_prio_0 & (_excluded_client_T_1 | (&request_opcode) | request_opcode == 3'h4) & req_clientBit;	// @[MSHR.scala:100:20, :102:17, :289:28, Parameters.scala:46:9, :270:{14,52}, :278:{77,87}]
  wire        _T_573 = io_allocate_valid & io_allocate_bits_repeat;	// @[MSHR.scala:515:40]
  wire        new_meta_hit = _T_573 ? (bad_grant ? meta_hit : _GEN_1) : io_directory_bits_hit;	// @[MSHR.scala:102:17, :151:22, :233:52, :237:34, :238:53, :261:20, :262:21, :515:{21,40}]
  wire        new_request_prio_2 = io_allocate_valid ? io_allocate_bits_prio_2 : request_prio_2;	// @[MSHR.scala:100:20, :516:24]
  wire        _T_574 = io_directory_valid | _T_573;	// @[MSHR.scala:515:40, :549:28]
  wire        new_meta_dirty = _T_573 ? _io_schedule_bits_dir_bits_data_WIRE_dirty : io_directory_bits_dirty;	// @[MSHR.scala:233:52, :261:20, :262:21, :515:{21,40}]
  wire [1:0]  new_meta_state = _T_573 ? _io_schedule_bits_dir_bits_data_WIRE_state : io_directory_bits_state;	// @[MSHR.scala:233:52, :261:20, :262:21, :515:{21,40}]
  wire        new_meta_clients = _T_573 ? _io_schedule_bits_dir_bits_data_WIRE_clients : io_directory_bits_clients;	// @[MSHR.scala:233:52, :261:20, :262:21, :515:{21,40}]
  wire        new_request_control = io_allocate_valid ? io_allocate_bits_control : request_control;	// @[MSHR.scala:100:20, :516:24]
  wire [2:0]  new_request_opcode = io_allocate_valid ? io_allocate_bits_opcode : request_opcode;	// @[MSHR.scala:100:20, :516:24]
  wire [2:0]  new_request_param = io_allocate_valid ? io_allocate_bits_param : request_param;	// @[MSHR.scala:100:20, :516:24]
  wire        _T_615 = new_request_opcode == 3'h6;	// @[MSHR.scala:516:24, Parameters.scala:270:14]
  wire        new_needT = ~(new_request_opcode[2]) | new_request_opcode == 3'h5 & new_request_param == 3'h1 | (_T_615 | (&new_request_opcode)) & (|new_request_param);	// @[MSHR.scala:516:24, Parameters.scala:268:{5,12}, :269:{13,33,42,70}, :270:{14,42,52,80,89}, :281:11]
  wire        new_clientBit = (io_allocate_valid ? io_allocate_bits_source : request_source) == 5'h10;	// @[MSHR.scala:100:20, :516:24, Parameters.scala:46:9]
  wire        _T_600 = ~new_meta_hit & (|new_meta_state);	// @[MSHR.scala:515:21, :616:{13,27,45}]
  wire        _GEN_4 = new_request_prio_2 | (new_request_control ? ~new_meta_hit : ~_T_600);	// @[MSHR.scala:515:21, :516:24, :563:22, :581:58, :595:14, :598:57, :601:27, :616:{27,58}, :617:19]
  wire        _GEN_5 = new_request_prio_2 | (new_request_control ? ~(new_meta_hit & new_meta_clients) : ~(_T_600 & new_meta_clients));	// @[MSHR.scala:515:21, :516:24, :560:22, :581:58, :598:57, :601:27, :605:69, :606:20, :616:{27,58}, :620:68, :621:20]
  wire        _T_606 = ~new_meta_hit | new_meta_state == 2'h1 & new_needT;	// @[MSHR.scala:110:22, :515:21, :616:13, :627:{27,46,57}, Parameters.scala:269:70]
  wire        _GEN_6 = new_request_prio_2 | new_request_control;	// @[MSHR.scala:516:24, :566:22, :581:58, :598:57, :627:72]
  wire        _GEN_7 = _GEN_6 | ~_T_606;	// @[MSHR.scala:566:22, :581:58, :598:57, :627:{27,72}, :628:19]
  wire        _T_614 = new_meta_hit & (new_needT | new_meta_state == 2'h2) & new_meta_clients & ~((_T_615 | (&new_request_opcode) | new_request_opcode == 3'h4) & new_clientBit);	// @[MSHR.scala:113:22, :515:21, :516:24, :519:26, :637:{24,42,53}, :638:33, Parameters.scala:46:9, :269:70, :270:{14,52}, :278:{77,87}]
  wire        _GEN_8 = _GEN_6 | ~_T_614;	// @[MSHR.scala:565:22, :566:22, :581:58, :598:57, :627:72, :637:53, :638:59, :639:18]
  wire        _T_617 = _T_615 | (&new_request_opcode);	// @[MSHR.scala:516:24, :646:49, Parameters.scala:270:{14,52}]
  wire        _GEN_9 = io_schedule_ready & no_wait;	// @[MSHR.scala:141:33, :185:83, :207:28, :216:{35,50}]
  wire        _T_33 = meta_valid & (|meta_state) & io_nestedwb_set == request_set & io_nestedwb_tag == meta_tag;	// @[MSHR.scala:100:20, :101:27, :102:17, :157:34, :158:{25,41,60}]
  wire        probe_bit = io_sinkc_bits_source == 5'h10;	// @[Parameters.scala:46:9]
  wire        _T_540 = io_sinkd_bits_opcode == 3'h4 | io_sinkd_bits_opcode == 3'h5;	// @[MSHR.scala:493:{32,42,66}, Parameters.scala:269:13, :278:87]
  wire        _GEN_10 = io_sinkd_valid & _T_540;	// @[MSHR.scala:149:17, :492:25, :493:{42,81}, :494:12]
  wire        last_probe = (probes_done | probe_bit) == (meta_clients & ~excluded_client);	// @[MSHR.scala:102:17, :152:24, :289:28, :299:53, :469:{33,46,64}, Parameters.scala:46:9]
  wire        _GEN_11 = io_sinkc_valid & last_probe;	// @[MSHR.scala:124:33, :469:46, :471:49, :480:22]
  wire        _GEN_12 = io_sinkc_valid & last_probe & io_sinkc_bits_last;	// @[MSHR.scala:125:33, :469:46, :471:49, :481:21]
  always @(posedge clock) begin
    if (reset) begin
      request_valid <= 1'h0;	// @[MSHR.scala:99:30]
      meta_valid <= 1'h0;	// @[MSHR.scala:99:30, :101:27]
      s_rprobe <= 1'h1;	// @[MSHR.scala:107:14, :123:33]
      w_rprobeackfirst <= 1'h1;	// @[MSHR.scala:107:14, :124:33]
      w_rprobeacklast <= 1'h1;	// @[MSHR.scala:107:14, :125:33]
      s_release <= 1'h1;	// @[MSHR.scala:107:14, :126:33]
      w_releaseack <= 1'h1;	// @[MSHR.scala:107:14, :127:33]
      s_pprobe <= 1'h1;	// @[MSHR.scala:107:14, :128:33]
      s_acquire <= 1'h1;	// @[MSHR.scala:107:14, :129:33]
      s_flush <= 1'h1;	// @[MSHR.scala:107:14, :130:33]
      w_grantfirst <= 1'h1;	// @[MSHR.scala:107:14, :131:33]
      w_grantlast <= 1'h1;	// @[MSHR.scala:107:14, :132:33]
      w_grant <= 1'h1;	// @[MSHR.scala:107:14, :133:33]
      w_pprobeackfirst <= 1'h1;	// @[MSHR.scala:107:14, :134:33]
      w_pprobeacklast <= 1'h1;	// @[MSHR.scala:107:14, :135:33]
      w_pprobeack <= 1'h1;	// @[MSHR.scala:107:14, :136:33]
      s_grantack <= 1'h1;	// @[MSHR.scala:107:14, :138:33]
      s_execute <= 1'h1;	// @[MSHR.scala:107:14, :139:33]
      w_grantack <= 1'h1;	// @[MSHR.scala:107:14, :140:33]
      s_writeback <= 1'h1;	// @[MSHR.scala:107:14, :141:33]
    end
    else begin
      request_valid <= io_allocate_valid | ~_GEN_9 & request_valid;	// @[MSHR.scala:99:30, :141:33, :207:28, :216:{35,50}, :218:20, :219:21, :542:28, :544:19]
      meta_valid <= _T_574 | ~_GEN_9 & meta_valid;	// @[MSHR.scala:99:30, :101:27, :141:33, :207:28, :216:{35,50}, :218:20, :219:21, :220:18, :549:{28,79}, :550:16]
      if (_T_574) begin	// @[MSHR.scala:549:28]
        s_rprobe <= _GEN_5;	// @[MSHR.scala:123:33, :560:22, :581:58, :598:57]
        w_rprobeackfirst <= _GEN_5;	// @[MSHR.scala:124:33, :560:22, :581:58, :598:57]
        w_rprobeacklast <= _GEN_5;	// @[MSHR.scala:125:33, :560:22, :581:58, :598:57]
        s_release <= _GEN_4;	// @[MSHR.scala:126:33, :563:22, :581:58, :598:57]
        w_releaseack <= _GEN_4;	// @[MSHR.scala:127:33, :563:22, :581:58, :598:57]
        s_pprobe <= _GEN_8;	// @[MSHR.scala:128:33, :565:22, :581:58, :598:57, :638:59]
        s_acquire <= _GEN_7;	// @[MSHR.scala:129:33, :566:22, :581:58, :598:57, :627:72]
        s_flush <= new_request_prio_2 | ~new_request_control;	// @[MSHR.scala:130:33, :516:24, :567:22, :581:58, :598:57, :599:15]
        w_grantfirst <= _GEN_7;	// @[MSHR.scala:131:33, :566:22, :581:58, :598:57, :627:72]
        w_grantlast <= _GEN_7;	// @[MSHR.scala:132:33, :566:22, :581:58, :598:57, :627:72]
        w_grant <= _GEN_7;	// @[MSHR.scala:133:33, :566:22, :581:58, :598:57, :627:72]
        w_pprobeackfirst <= _GEN_8;	// @[MSHR.scala:134:33, :565:22, :581:58, :598:57, :638:59]
        w_pprobeacklast <= _GEN_8;	// @[MSHR.scala:135:33, :565:22, :581:58, :598:57, :638:59]
        w_pprobeack <= _GEN_8;	// @[MSHR.scala:136:33, :565:22, :581:58, :598:57, :638:59]
        s_grantack <= _GEN_7;	// @[MSHR.scala:138:33, :566:22, :581:58, :598:57, :627:72]
        s_execute <= ~new_request_prio_2 & new_request_control;	// @[MSHR.scala:139:33, :516:24, :581:58, :582:17, :598:57]
        w_grantack <= _GEN_6 | ~_T_617;	// @[MSHR.scala:140:33, :566:22, :577:22, :581:58, :598:57, :627:72, :646:{49,88}, :647:20]
        if (new_request_prio_2)	// @[MSHR.scala:516:24]
          s_writeback <= ~((new_request_param == 3'h1 | new_request_param == 3'h2 | new_request_param == 3'h5) & new_meta_clients & new_clientBit | (new_request_param == 3'h0 | new_request_param == 3'h4) & new_meta_state == 2'h2 | new_request_opcode[0] & ~new_meta_dirty);	// @[MSHR.scala:113:22, :141:33, :515:21, :516:24, :578:22, :584:{31,35,38,55}, :585:21, :588:{38,56,67}, :589:21, :592:{38,85}, :593:21, Parameters.scala:46:9, :269:13, :270:89, :278:87, :281:{11,43,66,75}, :284:{11,34,43}]
        else	// @[MSHR.scala:516:24]
          s_writeback <= new_request_control | ~(~(new_request_opcode[2]) & new_meta_hit & ~new_meta_dirty | _T_617 | _T_614 | _T_606);	// @[MSHR.scala:141:33, :515:21, :516:24, :578:22, :598:57, :627:{27,72}, :633:21, :637:53, :638:59, :643:21, :646:{49,88}, :648:21, :651:{13,52,55,72}, :652:21, Parameters.scala:268:12]
      end
      else begin	// @[MSHR.scala:549:28]
        s_rprobe <= io_schedule_ready | s_rprobe;	// @[MSHR.scala:123:33, :207:28, :208:50]
        w_rprobeackfirst <= _GEN_11 | w_rprobeackfirst;	// @[MSHR.scala:124:33, :471:49, :480:22]
        w_rprobeacklast <= _GEN_12 | w_rprobeacklast;	// @[MSHR.scala:125:33, :471:49, :481:21]
        s_release <= io_schedule_ready & w_rprobeackfirst | s_release;	// @[MSHR.scala:124:33, :126:33, :207:28, :209:{35,50}]
        w_releaseack <= io_sinkd_valid & ~_T_540 & io_sinkd_bits_opcode == 3'h6 | w_releaseack;	// @[MSHR.scala:127:33, :492:25, :493:{42,81}, :505:{37,53}, Parameters.scala:270:14]
        s_pprobe <= io_schedule_ready | s_pprobe;	// @[MSHR.scala:128:33, :207:28, :210:50]
        s_acquire <= io_schedule_ready & s_release & s_pprobe | s_acquire;	// @[MSHR.scala:126:33, :128:33, :129:33, :207:28, :211:{35,50}]
        s_flush <= io_schedule_ready & w_releaseack | s_flush;	// @[MSHR.scala:127:33, :130:33, :207:28, :212:{35,50}]
        w_grantfirst <= _GEN_10 | w_grantfirst;	// @[MSHR.scala:131:33, :149:17, :492:25, :493:81, :494:12, :495:20]
        if (_GEN_10) begin	// @[MSHR.scala:149:17, :492:25, :493:81, :494:12]
          w_grantlast <= io_sinkd_bits_last;	// @[MSHR.scala:132:33]
          w_grant <= ~(|request_offset) | io_sinkd_bits_last;	// @[MSHR.scala:100:20, :133:33, :485:77, :500:{33,41}]
        end
        w_pprobeackfirst <= _GEN_11 | w_pprobeackfirst;	// @[MSHR.scala:124:33, :134:33, :471:49, :480:22, :482:22]
        w_pprobeacklast <= _GEN_12 | w_pprobeacklast;	// @[MSHR.scala:125:33, :135:33, :471:49, :481:21, :483:21]
        w_pprobeack <= io_sinkc_valid & last_probe & (io_sinkc_bits_last | ~(|request_offset)) | w_pprobeack;	// @[MSHR.scala:100:20, :136:33, :469:46, :471:49, :485:{59,77}, :486:17]
        s_grantack <= io_schedule_ready & w_grantfirst | s_grantack;	// @[MSHR.scala:131:33, :138:33, :207:28, :214:{35,50}]
        s_execute <= io_schedule_ready & w_pprobeack & w_grant | s_execute;	// @[MSHR.scala:133:33, :136:33, :139:33, :207:28, :215:{35,50}]
        w_grantack <= io_sinke_valid | w_grantack;	// @[MSHR.scala:140:33, :509:25, :510:16]
        s_writeback <= _GEN_9 | s_writeback;	// @[MSHR.scala:141:33, :207:28, :216:{35,50}]
      end
    end
    if (io_allocate_valid) begin
      request_prio_0 <= io_allocate_bits_prio_0;	// @[MSHR.scala:100:20]
      request_prio_1 <= io_allocate_bits_prio_1;	// @[MSHR.scala:100:20]
      request_prio_2 <= io_allocate_bits_prio_2;	// @[MSHR.scala:100:20]
      request_control <= io_allocate_bits_control;	// @[MSHR.scala:100:20]
      request_opcode <= io_allocate_bits_opcode;	// @[MSHR.scala:100:20]
      request_param <= io_allocate_bits_param;	// @[MSHR.scala:100:20]
      request_size <= io_allocate_bits_size;	// @[MSHR.scala:100:20]
      request_source <= io_allocate_bits_source;	// @[MSHR.scala:100:20]
      request_tag <= io_allocate_bits_tag;	// @[MSHR.scala:100:20]
      request_offset <= io_allocate_bits_offset;	// @[MSHR.scala:100:20]
      request_put <= io_allocate_bits_put;	// @[MSHR.scala:100:20]
      request_set <= io_allocate_bits_set;	// @[MSHR.scala:100:20]
    end
    if (_T_574) begin	// @[MSHR.scala:549:28]
      if (_T_573) begin	// @[MSHR.scala:515:40]
        meta_dirty <= _io_schedule_bits_dir_bits_data_WIRE_dirty;	// @[MSHR.scala:102:17, :233:52, :261:20, :262:21]
        if (bad_grant) begin	// @[MSHR.scala:151:22]
          meta_state <= _GEN_2;	// @[MSHR.scala:102:17, :262:21, :267:36, :273:36]
          meta_clients <= _GEN_3;	// @[MSHR.scala:102:17, :262:21, :268:36, :274:36]
        end
        else begin	// @[MSHR.scala:151:22]
          if (request_prio_2) begin	// @[MSHR.scala:100:20]
            if (_final_meta_writeback_state_T_2)	// @[MSHR.scala:235:64]
              meta_state <= 2'h3;	// @[MSHR.scala:102:17, :117:22]
            meta_clients <= _final_meta_writeback_clients_T_7;	// @[MSHR.scala:102:17, :236:50]
          end
          else if (request_control) begin	// @[MSHR.scala:100:20]
            if (meta_hit)	// @[MSHR.scala:102:17]
              meta_state <= 2'h0;	// @[MSHR.scala:102:17, :106:22]
            meta_clients <= _GEN;	// @[MSHR.scala:102:17, :225:38, :239:21, :242:36]
          end
          else begin	// @[MSHR.scala:100:20]
            if (req_needT)	// @[Parameters.scala:269:70]
              meta_state <= _final_meta_writeback_state_T_6;	// @[MSHR.scala:102:17, :248:40]
            else if (meta_hit) begin	// @[MSHR.scala:102:17]
              if (&meta_state)	// @[MSHR.scala:102:17, :231:81]
                meta_state <= _final_meta_writeback_state_T_9;	// @[MSHR.scala:102:17, :254:55]
              else	// @[MSHR.scala:231:81]
                meta_state <= _final_meta_writeback_state_T_13;	// @[MSHR.scala:102:17, Mux.scala:81:58]
            end
            else if (gotT)	// @[MSHR.scala:150:17]
              meta_state <= _final_meta_writeback_state_T_6;	// @[MSHR.scala:102:17, :248:40]
            else	// @[MSHR.scala:150:17]
              meta_state <= 2'h1;	// @[MSHR.scala:102:17, :110:22]
            meta_clients <= _final_meta_writeback_clients_T_14;	// @[MSHR.scala:102:17, :255:84]
          end
          meta_hit <= _GEN_1;	// @[MSHR.scala:102:17, :233:52, :237:34, :238:53]
        end
        if (~_GEN_0)	// @[MSHR.scala:225:38, :233:52, :238:53, :257:30]
          meta_tag <= request_tag;	// @[MSHR.scala:100:20, :102:17]
      end
      else begin	// @[MSHR.scala:515:40]
        meta_dirty <= io_directory_bits_dirty;	// @[MSHR.scala:102:17]
        meta_state <= io_directory_bits_state;	// @[MSHR.scala:102:17]
        meta_clients <= io_directory_bits_clients;	// @[MSHR.scala:102:17]
        meta_tag <= io_directory_bits_tag;	// @[MSHR.scala:102:17]
        meta_hit <= io_directory_bits_hit;	// @[MSHR.scala:102:17]
      end
    end
    else begin	// @[MSHR.scala:549:28]
      meta_dirty <= io_sinkc_valid & (|meta_state) & io_sinkc_bits_tag == meta_tag & io_sinkc_bits_data | (_T_33 ? io_nestedwb_c_set_dirty | ~io_nestedwb_b_clr_dirty & meta_dirty : meta_dirty);	// @[MSHR.scala:102:17, :157:34, :158:{41,74}, :159:{36,49}, :160:{36,49}, :471:49, :490:{55,91,104}]
      if (_T_33 & io_nestedwb_b_toB)	// @[MSHR.scala:102:17, :158:{41,74}, :161:{30,43}]
        meta_state <= 2'h1;	// @[MSHR.scala:102:17, :110:22]
      meta_hit <= ~(_T_33 & io_nestedwb_b_toN) & meta_hit;	// @[MSHR.scala:102:17, :158:{41,74}, :162:{30,41}]
    end
    if (~_T_574 | _T_573) begin	// @[MSHR.scala:102:17, :515:40, :549:{28,79}, :551:10]
    end
    else	// @[MSHR.scala:102:17, :549:79, :551:10]
      meta_way <= io_directory_bits_way;	// @[MSHR.scala:102:17]
    if (_GEN_10)	// @[MSHR.scala:149:17, :492:25, :493:81, :494:12]
      sink <= io_sinkd_bits_sink;	// @[MSHR.scala:149:17]
    gotT <= ~_T_574 & (_GEN_10 ? io_sinkd_bits_param == 3'h0 : gotT);	// @[MSHR.scala:102:17, :149:17, :150:17, :492:25, :493:81, :494:12, :503:{12,35}, :549:{28,79}, :551:10, :555:10, Parameters.scala:270:89]
    bad_grant <= ~_T_574 & (_GEN_10 ? io_sinkd_bits_denied : bad_grant);	// @[MSHR.scala:102:17, :149:17, :151:22, :492:25, :493:81, :494:12, :498:17, :549:{28,79}, :551:10, :556:15]
    probes_done <= ~_T_574 & (io_sinkc_valid & probe_bit | probes_done);	// @[MSHR.scala:102:17, :152:24, :471:49, :477:17, :549:{28,79}, :551:10, :552:17, Parameters.scala:46:9]
    probes_toN <= ~_T_574 & (io_sinkc_valid & (io_sinkc_bits_param == 3'h1 | io_sinkc_bits_param == 3'h2 | io_sinkc_bits_param == 3'h5) & probe_bit | probes_toN);	// @[MSHR.scala:102:17, :153:23, :471:49, :478:16, :549:{28,79}, :551:10, :553:16, Parameters.scala:46:9, :269:13, :281:{11,43,66,75}]
  end // always @(posedge)
  `ifndef SYNTHESIS
    wire             _GEN_13 = meta_valid & ~(|meta_state);	// @[MSHR.scala:101:27, :102:17, :106:{22,35}]
    wire             _GEN_14 = meta_valid & meta_state == 2'h2;	// @[MSHR.scala:101:27, :102:17, :113:{22,33}]
    wire  [3:0]      _GEN_15 = {2'h1, ~meta_clients, ~meta_dirty};	// @[MSHR.scala:102:17, :110:22, :114:14, :327:26, :329:32, :330:26]
    wire  [3:0]      _GEN_16 = {3'h1, ~meta_dirty};	// @[MSHR.scala:102:17, :327:26, :329:{26,32}, Parameters.scala:281:11]
    wire  [3:0]      _GEN_17 = {3'h0, ~meta_clients};	// @[MSHR.scala:102:17, :114:14, :327:26, :328:26, Parameters.scala:270:89]
    wire  [3:0][3:0] _GEN_18 = {{_GEN_15}, {_GEN_16}, {_GEN_17}, {{~(|meta_state), 3'h0}}};	// @[MSHR.scala:102:17, :106:22, :231:81, :301:53, :324:26, :327:26, :328:26, :329:26, :330:26, :331:26, Parameters.scala:270:89]
    wire  [3:0]      evict = meta_hit ? 4'h8 : _GEN_18[meta_state];	// @[MSHR.scala:102:17, :231:81, :301:53, :327:26, :328:26, :329:26, :330:26, :331:26, :333:{17,23}]
    wire  [3:0][3:0] _GEN_19 = {{_GEN_15}, {_GEN_16}, {_GEN_17}, {{~(|meta_state), 3'h0}}};	// @[MSHR.scala:102:17, :106:22, :231:81, :301:53, :324:26, :327:26, :328:26, :329:26, :330:26, :331:26, Parameters.scala:270:89]
    wire  [3:0]      before_0 = meta_hit ? _GEN_19[meta_state] : 4'h8;	// @[MSHR.scala:102:17, :231:81, :301:53, :327:26, :328:26, :329:26, :330:26, :331:26, :333:{17,23}]
    wire  [3:0]      _GEN_20 = {2'h1, ~_io_schedule_bits_dir_bits_data_WIRE_clients, ~_io_schedule_bits_dir_bits_data_WIRE_dirty};	// @[MSHR.scala:110:22, :233:52, :261:20, :262:21, :327:26, :328:32, :329:32, :330:26]
    wire  [3:0]      _GEN_21 = {3'h1, ~_io_schedule_bits_dir_bits_data_WIRE_dirty};	// @[MSHR.scala:233:52, :261:20, :262:21, :327:26, :329:{26,32}, Parameters.scala:281:11]
    wire  [3:0]      _GEN_22 = {3'h0, ~_io_schedule_bits_dir_bits_data_WIRE_clients};	// @[MSHR.scala:233:52, :261:20, :262:21, :327:26, :328:{26,32}, Parameters.scala:270:89]
    wire  [3:0][3:0] _GEN_23 = {{_GEN_20}, {_GEN_21}, {_GEN_22}, {{~(|_io_schedule_bits_dir_bits_data_WIRE_state), 3'h0}}};	// @[MSHR.scala:233:52, :261:20, :262:21, :324:26, :327:26, :328:26, :329:26, :330:26, :331:26, Parameters.scala:270:89]
    wire  [3:0]      after = _GEN_23[_io_schedule_bits_dir_bits_data_WIRE_state];	// @[MSHR.scala:233:52, :261:20, :262:21, :327:26, :328:26, :329:26, :330:26]
    wire             _T_58 = ~s_release & w_rprobeackfirst & io_schedule_ready;	// @[MSHR.scala:124:33, :126:33, :188:32, :373:42]
    wire             _T_93 = ~s_writeback & no_wait & io_schedule_ready;	// @[MSHR.scala:141:33, :185:83, :192:70, :384:35]
    wire             _T_131 = before_0 == 4'h8;	// @[MSHR.scala:327:26, :331:26, :333:{17,23}, :385:15]
    wire             _T_486 = after == 4'h1;	// @[MSHR.scala:327:26, :328:26, :374:13, :385:15]
    wire             _T_493 = after == 4'h0;	// @[MSHR.scala:324:26, :327:26, :328:26, :331:26, :386:15]
    wire             _T_500 = after == 4'h7;	// @[MSHR.scala:327:26, :328:26, :387:15]
    wire             _T_507 = after == 4'h5;	// @[MSHR.scala:327:26, :328:26, :388:15]
    wire             _T_517 = after == 4'h4;	// @[MSHR.scala:327:26, :328:26, :389:15]
    wire             _T_514 = after == 4'h6;	// @[MSHR.scala:327:26, :328:26, :390:15]
    wire             _T_520 = after == 4'h3;	// @[MSHR.scala:327:26, :328:26, :391:15]
    wire             _T_476 = after == 4'h2;	// @[MSHR.scala:327:26, :328:26, :392:15]
    wire             _T_187 = before_0 == 4'h1;	// @[MSHR.scala:327:26, :333:{17,23}, :374:13, :394:15]
    wire             _T_479 = after == 4'h8;	// @[MSHR.scala:327:26, :328:26, :331:26, :394:15]
    wire             _T_243 = before_0 == 4'h0;	// @[MSHR.scala:324:26, :327:26, :331:26, :333:{17,23}, :403:15]
    wire             _T_291 = before_0 == 4'h7;	// @[MSHR.scala:327:26, :333:{17,23}, :387:15, :412:15]
    wire             _T_335 = before_0 == 4'h5;	// @[MSHR.scala:327:26, :333:{17,23}, :388:15, :421:15]
    wire             _T_391 = before_0 == 4'h6;	// @[MSHR.scala:327:26, :333:{17,23}, :390:15, :430:15]
    wire             _T_439 = before_0 == 4'h4;	// @[MSHR.scala:327:26, :333:{17,23}, :389:15, :439:15]
    wire             _T_475 = before_0 == 4'h3;	// @[MSHR.scala:327:26, :333:{17,23}, :391:15, :448:15]
    wire             _T_519 = before_0 == 4'h2;	// @[MSHR.scala:327:26, :333:{17,23}, :392:15, :457:15]
    wire  [3:0][3:0] _GEN_24 = {{_GEN_20}, {_GEN_21}, {_GEN_22}, {{~(|_io_schedule_bits_dir_bits_data_WIRE_state), 3'h0}}};	// @[MSHR.scala:233:52, :261:20, :262:21, :324:26, :327:26, :328:26, :329:26, :330:26, :331:26, Parameters.scala:270:89]
    wire  [3:0]      prior = _GEN_24[_io_schedule_bits_dir_bits_data_WIRE_state];	// @[MSHR.scala:233:52, :261:20, :262:21, :327:26, :328:26, :329:26, :330:26]
    always @(posedge clock) begin	// @[MSHR.scala:107:14]
      if (_GEN_13 & ~reset & meta_clients) begin	// @[MSHR.scala:102:17, :106:35, :107:14]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:107:14]
          $error("Assertion failed\n    at MSHR.scala:107 assert (!meta.clients.orR)\n");	// @[MSHR.scala:107:14]
        if (`STOP_COND_)	// @[MSHR.scala:107:14]
          $fatal;	// @[MSHR.scala:107:14]
      end
      if (_GEN_13 & ~reset & meta_dirty) begin	// @[MSHR.scala:102:17, :106:35, :108:14]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:108:14]
          $error("Assertion failed\n    at MSHR.scala:108 assert (!meta.dirty)\n");	// @[MSHR.scala:108:14]
        if (`STOP_COND_)	// @[MSHR.scala:108:14]
          $fatal;	// @[MSHR.scala:108:14]
      end
      if (meta_valid & meta_state == 2'h1 & ~reset & meta_dirty) begin	// @[MSHR.scala:101:27, :102:17, :110:22, :111:14]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:111:14]
          $error("Assertion failed\n    at MSHR.scala:111 assert (!meta.dirty)\n");	// @[MSHR.scala:111:14]
        if (`STOP_COND_)	// @[MSHR.scala:111:14]
          $fatal;	// @[MSHR.scala:111:14]
      end
      if (_GEN_14 & ~reset & ~meta_clients) begin	// @[MSHR.scala:102:17, :113:33, :114:14]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:114:14]
          $error("Assertion failed\n    at MSHR.scala:114 assert (meta.clients.orR)\n");	// @[MSHR.scala:114:14]
        if (`STOP_COND_)	// @[MSHR.scala:114:14]
          $fatal;	// @[MSHR.scala:114:14]
      end
      if (_GEN_14 & ~reset & meta_clients & meta_clients - 1'h1) begin	// @[MSHR.scala:102:17, :113:33, :115:{14,45}]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:115:14]
          $error("Assertion failed\n    at MSHR.scala:115 assert ((meta.clients & (meta.clients - 1.U)) === 0.U) // at most one\n");	// @[MSHR.scala:115:14]
        if (`STOP_COND_)	// @[MSHR.scala:115:14]
          $fatal;	// @[MSHR.scala:115:14]
      end
      if (~reset & ~(~(meta_valid & w_releaseack & w_rprobeacklast & w_pprobeacklast & ~w_grantfirst) | ~(~meta_valid | (~w_releaseack | ~w_rprobeacklast | ~w_pprobeacklast) & ~w_grantfirst))) begin	// @[MSHR.scala:101:27, :125:33, :127:33, :131:33, :135:33, :170:{28,40,45,62,79,82,100,103}, :171:93, :181:{10,11,33,36}]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:181:10]
          $error("Assertion failed\n    at MSHR.scala:181 assert (!io.status.bits.nestB || !io.status.bits.blockB)\n");	// @[MSHR.scala:181:10]
        if (`STOP_COND_)	// @[MSHR.scala:181:10]
          $fatal;	// @[MSHR.scala:181:10]
      end
      if (~reset & ~(~_io_status_bits_nestC_output | meta_valid)) begin	// @[MSHR.scala:101:27, :175:39, :182:{10,11,33}]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:182:10]
          $error("Assertion failed\n    at MSHR.scala:182 assert (!io.status.bits.nestC || !io.status.bits.blockC)\n");	// @[MSHR.scala:182:10]
        if (`STOP_COND_)	// @[MSHR.scala:182:10]
          $fatal;	// @[MSHR.scala:182:10]
      end
      if (bad_grant & meta_hit & ~reset & ~(~meta_valid | meta_state == 2'h1)) begin	// @[MSHR.scala:101:27, :102:17, :110:22, :151:22, :170:28, :264:{14,27,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:264:14]
          $error("Assertion failed\n    at MSHR.scala:264 assert (!meta_valid || meta.state === BRANCH)\n");	// @[MSHR.scala:264:14]
        if (`STOP_COND_)	// @[MSHR.scala:264:14]
          $fatal;	// @[MSHR.scala:264:14]
      end
      if (_T_58 & ~reset & evict == 4'h1) begin	// @[MSHR.scala:327:26, :333:{17,23}, :373:42, :374:13]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:374:13]
          $error("Assertion failed: State transition from S_BRANCH to evicted should be impossible (false,true,true,false,true)\n    at MSHR.scala:356 assert(!(evict === from.code), cf\"State transition from ${from} to evicted should be impossible ${cfg}\")\n");	// @[MSHR.scala:374:13]
        if (`STOP_COND_)	// @[MSHR.scala:374:13]
          $fatal;	// @[MSHR.scala:374:13]
      end
      if (_T_58 & ~reset & before_0 == 4'h1) begin	// @[MSHR.scala:327:26, :333:{17,23}, :373:42, :374:13]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:374:13]
          $error("Assertion failed: State transition from S_BRANCH to flushed should be impossible (false,true,true,false,true)\n    at MSHR.scala:361 assert(!(before === from.code), cf\"State transition from ${from} to flushed should be impossible ${cfg}\")\n");	// @[MSHR.scala:374:13]
        if (`STOP_COND_)	// @[MSHR.scala:374:13]
          $fatal;	// @[MSHR.scala:374:13]
      end
      if (_T_58 & ~reset & evict == 4'h0) begin	// @[MSHR.scala:324:26, :327:26, :331:26, :333:{17,23}, :373:42, :375:13]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:375:13]
          $error("Assertion failed: State transition from S_BRANCH_C to evicted should be impossible (false,true,true,false,true)\n    at MSHR.scala:356 assert(!(evict === from.code), cf\"State transition from ${from} to evicted should be impossible ${cfg}\")\n");	// @[MSHR.scala:375:13]
        if (`STOP_COND_)	// @[MSHR.scala:375:13]
          $fatal;	// @[MSHR.scala:375:13]
      end
      if (_T_58 & ~reset & before_0 == 4'h0) begin	// @[MSHR.scala:324:26, :327:26, :331:26, :333:{17,23}, :373:42, :375:13]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:375:13]
          $error("Assertion failed: State transition from S_BRANCH_C to flushed should be impossible (false,true,true,false,true)\n    at MSHR.scala:361 assert(!(before === from.code), cf\"State transition from ${from} to flushed should be impossible ${cfg}\")\n");	// @[MSHR.scala:375:13]
        if (`STOP_COND_)	// @[MSHR.scala:375:13]
          $fatal;	// @[MSHR.scala:375:13]
      end
      if (_T_93 & ~reset & _T_131 & _T_486) begin	// @[MSHR.scala:384:35, :385:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:385:15]
          $error("Assertion failed: State transition from S_INVALID to S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:385:15]
        if (`STOP_COND_)	// @[MSHR.scala:385:15]
          $fatal;	// @[MSHR.scala:385:15]
      end
      if (_T_93 & ~reset & _T_131 & _T_493) begin	// @[MSHR.scala:384:35, :385:15, :386:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:386:15]
          $error("Assertion failed: State transition from S_INVALID to S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:386:15]
        if (`STOP_COND_)	// @[MSHR.scala:386:15]
          $fatal;	// @[MSHR.scala:386:15]
      end
      if (_T_93 & ~reset & _T_131 & _T_507) begin	// @[MSHR.scala:384:35, :385:15, :388:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:388:15]
          $error("Assertion failed: State transition from S_INVALID to S_TIP_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:388:15]
        if (`STOP_COND_)	// @[MSHR.scala:388:15]
          $fatal;	// @[MSHR.scala:388:15]
      end
      if (_T_93 & ~reset & _T_131 & _T_517) begin	// @[MSHR.scala:384:35, :385:15, :389:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:389:15]
          $error("Assertion failed: State transition from S_INVALID to S_TIP_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:389:15]
        if (`STOP_COND_)	// @[MSHR.scala:389:15]
          $fatal;	// @[MSHR.scala:389:15]
      end
      if (_T_93 & ~reset & _T_131 & _T_476) begin	// @[MSHR.scala:384:35, :385:15, :392:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:392:15]
          $error("Assertion failed: State transition from S_INVALID to S_TRUNK_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:392:15]
        if (`STOP_COND_)	// @[MSHR.scala:392:15]
          $fatal;	// @[MSHR.scala:392:15]
      end
      if (_T_93 & ~reset & _T_187 & _T_479) begin	// @[MSHR.scala:384:35, :394:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:394:15]
          $error("Assertion failed: State transition from S_BRANCH to S_INVALID should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:394:15]
        if (`STOP_COND_)	// @[MSHR.scala:394:15]
          $fatal;	// @[MSHR.scala:394:15]
      end
      if (_T_93 & ~reset & _T_187 & _T_493) begin	// @[MSHR.scala:384:35, :386:15, :394:15, :395:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:395:15]
          $error("Assertion failed: State transition from S_BRANCH to S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:395:15]
        if (`STOP_COND_)	// @[MSHR.scala:395:15]
          $fatal;	// @[MSHR.scala:395:15]
      end
      if (_T_93 & ~reset & _T_187 & _T_500) begin	// @[MSHR.scala:384:35, :387:15, :394:15, :396:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:396:15]
          $error("Assertion failed: State transition from S_BRANCH to S_TIP should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:396:15]
        if (`STOP_COND_)	// @[MSHR.scala:396:15]
          $fatal;	// @[MSHR.scala:396:15]
      end
      if (_T_93 & ~reset & _T_187 & _T_507) begin	// @[MSHR.scala:384:35, :388:15, :394:15, :397:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:397:15]
          $error("Assertion failed: State transition from S_BRANCH to S_TIP_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:397:15]
        if (`STOP_COND_)	// @[MSHR.scala:397:15]
          $fatal;	// @[MSHR.scala:397:15]
      end
      if (_T_93 & ~reset & _T_187 & _T_517) begin	// @[MSHR.scala:384:35, :389:15, :394:15, :398:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:398:15]
          $error("Assertion failed: State transition from S_BRANCH to S_TIP_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:398:15]
        if (`STOP_COND_)	// @[MSHR.scala:398:15]
          $fatal;	// @[MSHR.scala:398:15]
      end
      if (_T_93 & ~reset & _T_187 & _T_514) begin	// @[MSHR.scala:384:35, :390:15, :394:15, :399:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:399:15]
          $error("Assertion failed: State transition from S_BRANCH to S_TIP_D should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:399:15]
        if (`STOP_COND_)	// @[MSHR.scala:399:15]
          $fatal;	// @[MSHR.scala:399:15]
      end
      if (_T_93 & ~reset & _T_187 & _T_520) begin	// @[MSHR.scala:384:35, :391:15, :394:15, :400:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:400:15]
          $error("Assertion failed: State transition from S_BRANCH to S_TRUNK_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:400:15]
        if (`STOP_COND_)	// @[MSHR.scala:400:15]
          $fatal;	// @[MSHR.scala:400:15]
      end
      if (_T_93 & ~reset & _T_187 & _T_476) begin	// @[MSHR.scala:384:35, :392:15, :394:15, :401:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:401:15]
          $error("Assertion failed: State transition from S_BRANCH to S_TRUNK_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:401:15]
        if (`STOP_COND_)	// @[MSHR.scala:401:15]
          $fatal;	// @[MSHR.scala:401:15]
      end
      if (_T_93 & ~reset & _T_243 & _T_479) begin	// @[MSHR.scala:384:35, :394:15, :403:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:403:15]
          $error("Assertion failed: State transition from S_BRANCH_C to S_INVALID should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:403:15]
        if (`STOP_COND_)	// @[MSHR.scala:403:15]
          $fatal;	// @[MSHR.scala:403:15]
      end
      if (_T_93 & ~reset & _T_243 & _T_486) begin	// @[MSHR.scala:384:35, :385:15, :403:15, :404:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:404:15]
          $error("Assertion failed: State transition from S_BRANCH_C to S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:404:15]
        if (`STOP_COND_)	// @[MSHR.scala:404:15]
          $fatal;	// @[MSHR.scala:404:15]
      end
      if (_T_93 & ~reset & _T_243 & _T_500) begin	// @[MSHR.scala:384:35, :387:15, :403:15, :405:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:405:15]
          $error("Assertion failed: State transition from S_BRANCH_C to S_TIP should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:405:15]
        if (`STOP_COND_)	// @[MSHR.scala:405:15]
          $fatal;	// @[MSHR.scala:405:15]
      end
      if (_T_93 & ~reset & _T_243 & _T_507) begin	// @[MSHR.scala:384:35, :388:15, :403:15, :406:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:406:15]
          $error("Assertion failed: State transition from S_BRANCH_C to S_TIP_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:406:15]
        if (`STOP_COND_)	// @[MSHR.scala:406:15]
          $fatal;	// @[MSHR.scala:406:15]
      end
      if (_T_93 & ~reset & _T_243 & _T_514) begin	// @[MSHR.scala:384:35, :390:15, :403:15, :407:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:407:15]
          $error("Assertion failed: State transition from S_BRANCH_C to S_TIP_D should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:407:15]
        if (`STOP_COND_)	// @[MSHR.scala:407:15]
          $fatal;	// @[MSHR.scala:407:15]
      end
      if (_T_93 & ~reset & _T_243 & _T_517) begin	// @[MSHR.scala:384:35, :389:15, :403:15, :408:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:408:15]
          $error("Assertion failed: State transition from S_BRANCH_C to S_TIP_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:408:15]
        if (`STOP_COND_)	// @[MSHR.scala:408:15]
          $fatal;	// @[MSHR.scala:408:15]
      end
      if (_T_93 & ~reset & _T_243 & _T_520) begin	// @[MSHR.scala:384:35, :391:15, :403:15, :409:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:409:15]
          $error("Assertion failed: State transition from S_BRANCH_C to S_TRUNK_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:409:15]
        if (`STOP_COND_)	// @[MSHR.scala:409:15]
          $fatal;	// @[MSHR.scala:409:15]
      end
      if (_T_93 & ~reset & _T_243 & _T_476) begin	// @[MSHR.scala:384:35, :392:15, :403:15, :410:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:410:15]
          $error("Assertion failed: State transition from S_BRANCH_C to S_TRUNK_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:410:15]
        if (`STOP_COND_)	// @[MSHR.scala:410:15]
          $fatal;	// @[MSHR.scala:410:15]
      end
      if (_T_93 & ~reset & _T_291 & _T_479) begin	// @[MSHR.scala:384:35, :394:15, :412:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:412:15]
          $error("Assertion failed: State transition from S_TIP to S_INVALID should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:412:15]
        if (`STOP_COND_)	// @[MSHR.scala:412:15]
          $fatal;	// @[MSHR.scala:412:15]
      end
      if (_T_93 & ~reset & _T_291 & _T_486) begin	// @[MSHR.scala:384:35, :385:15, :412:15, :413:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:413:15]
          $error("Assertion failed: State transition from S_TIP to S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:413:15]
        if (`STOP_COND_)	// @[MSHR.scala:413:15]
          $fatal;	// @[MSHR.scala:413:15]
      end
      if (_T_93 & ~reset & _T_291 & _T_493) begin	// @[MSHR.scala:384:35, :386:15, :412:15, :414:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:414:15]
          $error("Assertion failed: State transition from S_TIP to S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:414:15]
        if (`STOP_COND_)	// @[MSHR.scala:414:15]
          $fatal;	// @[MSHR.scala:414:15]
      end
      if (_T_93 & ~reset & _T_291 & _T_507) begin	// @[MSHR.scala:384:35, :388:15, :412:15, :415:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:415:15]
          $error("Assertion failed: State transition from S_TIP to S_TIP_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:415:15]
        if (`STOP_COND_)	// @[MSHR.scala:415:15]
          $fatal;	// @[MSHR.scala:415:15]
      end
      if (_T_93 & ~reset & _T_291 & _T_517) begin	// @[MSHR.scala:384:35, :389:15, :412:15, :417:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:417:15]
          $error("Assertion failed: State transition from S_TIP to S_TIP_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:417:15]
        if (`STOP_COND_)	// @[MSHR.scala:417:15]
          $fatal;	// @[MSHR.scala:417:15]
      end
      if (_T_93 & ~reset & _T_291 & _T_476) begin	// @[MSHR.scala:384:35, :392:15, :412:15, :419:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:419:15]
          $error("Assertion failed: State transition from S_TIP to S_TRUNK_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:419:15]
        if (`STOP_COND_)	// @[MSHR.scala:419:15]
          $fatal;	// @[MSHR.scala:419:15]
      end
      if (_T_93 & ~reset & _T_335 & _T_479) begin	// @[MSHR.scala:384:35, :394:15, :421:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:421:15]
          $error("Assertion failed: State transition from S_TIP_C to S_INVALID should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:421:15]
        if (`STOP_COND_)	// @[MSHR.scala:421:15]
          $fatal;	// @[MSHR.scala:421:15]
      end
      if (_T_93 & ~reset & _T_335 & _T_486) begin	// @[MSHR.scala:384:35, :385:15, :421:15, :422:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:422:15]
          $error("Assertion failed: State transition from S_TIP_C to S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:422:15]
        if (`STOP_COND_)	// @[MSHR.scala:422:15]
          $fatal;	// @[MSHR.scala:422:15]
      end
      if (_T_93 & ~reset & _T_335 & _T_493) begin	// @[MSHR.scala:384:35, :386:15, :421:15, :423:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:423:15]
          $error("Assertion failed: State transition from S_TIP_C to S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:423:15]
        if (`STOP_COND_)	// @[MSHR.scala:423:15]
          $fatal;	// @[MSHR.scala:423:15]
      end
      if (_T_93 & ~reset & _T_335 & _T_517) begin	// @[MSHR.scala:384:35, :389:15, :421:15, :426:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:426:15]
          $error("Assertion failed: State transition from S_TIP_C to S_TIP_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:426:15]
        if (`STOP_COND_)	// @[MSHR.scala:426:15]
          $fatal;	// @[MSHR.scala:426:15]
      end
      if (_T_93 & ~reset & _T_335 & _T_476) begin	// @[MSHR.scala:384:35, :392:15, :421:15, :428:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:428:15]
          $error("Assertion failed: State transition from S_TIP_C to S_TRUNK_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:428:15]
        if (`STOP_COND_)	// @[MSHR.scala:428:15]
          $fatal;	// @[MSHR.scala:428:15]
      end
      if (_T_93 & ~reset & _T_391 & _T_479) begin	// @[MSHR.scala:384:35, :394:15, :430:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:430:15]
          $error("Assertion failed: State transition from S_TIP_D to S_INVALID should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:430:15]
        if (`STOP_COND_)	// @[MSHR.scala:430:15]
          $fatal;	// @[MSHR.scala:430:15]
      end
      if (_T_93 & ~reset & _T_391 & _T_486) begin	// @[MSHR.scala:384:35, :385:15, :430:15, :431:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:431:15]
          $error("Assertion failed: State transition from S_TIP_D to S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:431:15]
        if (`STOP_COND_)	// @[MSHR.scala:431:15]
          $fatal;	// @[MSHR.scala:431:15]
      end
      if (_T_93 & ~reset & _T_391 & _T_493) begin	// @[MSHR.scala:384:35, :386:15, :430:15, :432:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:432:15]
          $error("Assertion failed: State transition from S_TIP_D to S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:432:15]
        if (`STOP_COND_)	// @[MSHR.scala:432:15]
          $fatal;	// @[MSHR.scala:432:15]
      end
      if (_T_93 & ~reset & _T_391 & _T_500) begin	// @[MSHR.scala:384:35, :387:15, :430:15, :433:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:433:15]
          $error("Assertion failed: State transition from S_TIP_D to S_TIP should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:433:15]
        if (`STOP_COND_)	// @[MSHR.scala:433:15]
          $fatal;	// @[MSHR.scala:433:15]
      end
      if (_T_93 & ~reset & _T_391 & _T_507) begin	// @[MSHR.scala:384:35, :388:15, :430:15, :434:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:434:15]
          $error("Assertion failed: State transition from S_TIP_D to S_TIP_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:434:15]
        if (`STOP_COND_)	// @[MSHR.scala:434:15]
          $fatal;	// @[MSHR.scala:434:15]
      end
      if (_T_93 & ~reset & _T_391 & _T_517) begin	// @[MSHR.scala:384:35, :389:15, :430:15, :435:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:435:15]
          $error("Assertion failed: State transition from S_TIP_D to S_TIP_CD should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:435:15]
        if (`STOP_COND_)	// @[MSHR.scala:435:15]
          $fatal;	// @[MSHR.scala:435:15]
      end
      if (_T_93 & ~reset & _T_391 & _T_520) begin	// @[MSHR.scala:384:35, :391:15, :430:15, :436:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:436:15]
          $error("Assertion failed: State transition from S_TIP_D to S_TRUNK_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:436:15]
        if (`STOP_COND_)	// @[MSHR.scala:436:15]
          $fatal;	// @[MSHR.scala:436:15]
      end
      if (_T_93 & ~reset & _T_439 & _T_479) begin	// @[MSHR.scala:384:35, :394:15, :439:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:439:15]
          $error("Assertion failed: State transition from S_TIP_CD to S_INVALID should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:439:15]
        if (`STOP_COND_)	// @[MSHR.scala:439:15]
          $fatal;	// @[MSHR.scala:439:15]
      end
      if (_T_93 & ~reset & _T_439 & _T_486) begin	// @[MSHR.scala:384:35, :385:15, :439:15, :440:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:440:15]
          $error("Assertion failed: State transition from S_TIP_CD to S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:440:15]
        if (`STOP_COND_)	// @[MSHR.scala:440:15]
          $fatal;	// @[MSHR.scala:440:15]
      end
      if (_T_93 & ~reset & _T_439 & _T_493) begin	// @[MSHR.scala:384:35, :386:15, :439:15, :441:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:441:15]
          $error("Assertion failed: State transition from S_TIP_CD to S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:441:15]
        if (`STOP_COND_)	// @[MSHR.scala:441:15]
          $fatal;	// @[MSHR.scala:441:15]
      end
      if (_T_93 & ~reset & _T_439 & _T_500) begin	// @[MSHR.scala:384:35, :387:15, :439:15, :442:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:442:15]
          $error("Assertion failed: State transition from S_TIP_CD to S_TIP should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:442:15]
        if (`STOP_COND_)	// @[MSHR.scala:442:15]
          $fatal;	// @[MSHR.scala:442:15]
      end
      if (_T_93 & ~reset & _T_439 & _T_507) begin	// @[MSHR.scala:384:35, :388:15, :439:15, :443:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:443:15]
          $error("Assertion failed: State transition from S_TIP_CD to S_TIP_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:443:15]
        if (`STOP_COND_)	// @[MSHR.scala:443:15]
          $fatal;	// @[MSHR.scala:443:15]
      end
      if (_T_93 & ~reset & _T_439 & _T_520) begin	// @[MSHR.scala:384:35, :391:15, :439:15, :445:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:445:15]
          $error("Assertion failed: State transition from S_TIP_CD to S_TRUNK_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:445:15]
        if (`STOP_COND_)	// @[MSHR.scala:445:15]
          $fatal;	// @[MSHR.scala:445:15]
      end
      if (_T_93 & ~reset & _T_475 & _T_479) begin	// @[MSHR.scala:384:35, :394:15, :448:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:448:15]
          $error("Assertion failed: State transition from S_TRUNK_C to S_INVALID should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:448:15]
        if (`STOP_COND_)	// @[MSHR.scala:448:15]
          $fatal;	// @[MSHR.scala:448:15]
      end
      if (_T_93 & ~reset & _T_475 & _T_486) begin	// @[MSHR.scala:384:35, :385:15, :448:15, :449:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:449:15]
          $error("Assertion failed: State transition from S_TRUNK_C to S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:449:15]
        if (`STOP_COND_)	// @[MSHR.scala:449:15]
          $fatal;	// @[MSHR.scala:449:15]
      end
      if (_T_93 & ~reset & _T_475 & _T_493) begin	// @[MSHR.scala:384:35, :386:15, :448:15, :450:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:450:15]
          $error("Assertion failed: State transition from S_TRUNK_C to S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:450:15]
        if (`STOP_COND_)	// @[MSHR.scala:450:15]
          $fatal;	// @[MSHR.scala:450:15]
      end
      if (_T_93 & ~reset & _T_519 & _T_479) begin	// @[MSHR.scala:384:35, :394:15, :457:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:457:15]
          $error("Assertion failed: State transition from S_TRUNK_CD to S_INVALID should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:457:15]
        if (`STOP_COND_)	// @[MSHR.scala:457:15]
          $fatal;	// @[MSHR.scala:457:15]
      end
      if (_T_93 & ~reset & _T_519 & _T_486) begin	// @[MSHR.scala:384:35, :385:15, :457:15, :458:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:458:15]
          $error("Assertion failed: State transition from S_TRUNK_CD to S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:458:15]
        if (`STOP_COND_)	// @[MSHR.scala:458:15]
          $fatal;	// @[MSHR.scala:458:15]
      end
      if (_T_93 & ~reset & _T_519 & _T_493) begin	// @[MSHR.scala:384:35, :386:15, :457:15, :459:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:459:15]
          $error("Assertion failed: State transition from S_TRUNK_CD to S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:459:15]
        if (`STOP_COND_)	// @[MSHR.scala:459:15]
          $fatal;	// @[MSHR.scala:459:15]
      end
      if (_T_93 & ~reset & _T_519 & _T_500) begin	// @[MSHR.scala:384:35, :387:15, :457:15, :460:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:460:15]
          $error("Assertion failed: State transition from S_TRUNK_CD to S_TIP should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:460:15]
        if (`STOP_COND_)	// @[MSHR.scala:460:15]
          $fatal;	// @[MSHR.scala:460:15]
      end
      if (_T_93 & ~reset & _T_519 & _T_507) begin	// @[MSHR.scala:384:35, :388:15, :457:15, :461:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:461:15]
          $error("Assertion failed: State transition from S_TRUNK_CD to S_TIP_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:461:15]
        if (`STOP_COND_)	// @[MSHR.scala:461:15]
          $fatal;	// @[MSHR.scala:461:15]
      end
      if (_T_93 & ~reset & _T_519 & _T_520) begin	// @[MSHR.scala:384:35, :391:15, :457:15, :464:15]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:464:15]
          $error("Assertion failed: State transition from S_TRUNK_CD to S_TRUNK_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:369 assert(!(before === from.code && after === to.code), cf\"State transition from ${from} to ${to} should be impossible ${cfg}\")\n");	// @[MSHR.scala:464:15]
        if (`STOP_COND_)	// @[MSHR.scala:464:15]
          $fatal;	// @[MSHR.scala:464:15]
      end
      if (_T_573 & ~reset & prior == 4'h1) begin	// @[MSHR.scala:327:26, :328:26, :374:13, :515:40, :532:11]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:532:11]
          $error("Assertion failed: State bypass from S_BRANCH should be impossible (false,true,true,false,true)\n    at MSHR.scala:526 assert(!(prior === from.code), cf\"State bypass from ${from} should be impossible ${cfg}\")\n");	// @[MSHR.scala:532:11]
        if (`STOP_COND_)	// @[MSHR.scala:532:11]
          $fatal;	// @[MSHR.scala:532:11]
      end
      if (_T_573 & ~reset & prior == 4'h0) begin	// @[MSHR.scala:324:26, :327:26, :328:26, :331:26, :515:40, :533:11]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:533:11]
          $error("Assertion failed: State bypass from S_BRANCH_C should be impossible (false,true,true,false,true)\n    at MSHR.scala:526 assert(!(prior === from.code), cf\"State bypass from ${from} should be impossible ${cfg}\")\n");	// @[MSHR.scala:533:11]
        if (`STOP_COND_)	// @[MSHR.scala:533:11]
          $fatal;	// @[MSHR.scala:533:11]
      end
      if (io_allocate_valid & ~reset & ~(~request_valid | no_wait & io_schedule_ready & _io_schedule_valid_output)) begin	// @[MSHR.scala:99:30, :185:83, :195:105, :543:{12,13,28,40}]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:543:12]
          $error("Assertion failed\n    at MSHR.scala:543 assert (!request_valid || (no_wait && io.schedule.fire))\n");	// @[MSHR.scala:543:12]
        if (`STOP_COND_)	// @[MSHR.scala:543:12]
          $fatal;	// @[MSHR.scala:543:12]
      end
      if (_T_574 & new_request_prio_2 & ~reset & ~new_meta_hit) begin	// @[MSHR.scala:515:21, :516:24, :549:28, :595:14]
        if (`ASSERT_VERBOSE_COND_)	// @[MSHR.scala:595:14]
          $error("Assertion failed\n    at MSHR.scala:595 assert (new_meta.hit)\n");	// @[MSHR.scala:595:14]
        if (`STOP_COND_)	// @[MSHR.scala:595:14]
          $fatal;	// @[MSHR.scala:595:14]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0]     _RANDOM_0;
    logic [31:0]     _RANDOM_1;
    logic [31:0]     _RANDOM_2;
    logic [31:0]     _RANDOM_3;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        request_valid = _RANDOM_0[0];	// @[MSHR.scala:99:30]
        request_prio_0 = _RANDOM_0[1];	// @[MSHR.scala:99:30, :100:20]
        request_prio_1 = _RANDOM_0[2];	// @[MSHR.scala:99:30, :100:20]
        request_prio_2 = _RANDOM_0[3];	// @[MSHR.scala:99:30, :100:20]
        request_control = _RANDOM_0[4];	// @[MSHR.scala:99:30, :100:20]
        request_opcode = _RANDOM_0[7:5];	// @[MSHR.scala:99:30, :100:20]
        request_param = _RANDOM_0[10:8];	// @[MSHR.scala:99:30, :100:20]
        request_size = _RANDOM_0[13:11];	// @[MSHR.scala:99:30, :100:20]
        request_source = _RANDOM_0[18:14];	// @[MSHR.scala:99:30, :100:20]
        request_tag = _RANDOM_0[30:19];	// @[MSHR.scala:99:30, :100:20]
        request_offset = {_RANDOM_0[31], _RANDOM_1[4:0]};	// @[MSHR.scala:99:30, :100:20]
        request_put = _RANDOM_1[10:5];	// @[MSHR.scala:100:20]
        request_set = _RANDOM_1[20:11];	// @[MSHR.scala:100:20]
        meta_valid = _RANDOM_1[21];	// @[MSHR.scala:100:20, :101:27]
        meta_dirty = _RANDOM_1[22];	// @[MSHR.scala:100:20, :102:17]
        meta_state = _RANDOM_1[24:23];	// @[MSHR.scala:100:20, :102:17]
        meta_clients = _RANDOM_1[25];	// @[MSHR.scala:100:20, :102:17]
        meta_tag = {_RANDOM_1[31:26], _RANDOM_2[5:0]};	// @[MSHR.scala:100:20, :102:17]
        meta_hit = _RANDOM_2[6];	// @[MSHR.scala:102:17]
        meta_way = _RANDOM_2[9:7];	// @[MSHR.scala:102:17]
        s_rprobe = _RANDOM_2[10];	// @[MSHR.scala:102:17, :123:33]
        w_rprobeackfirst = _RANDOM_2[11];	// @[MSHR.scala:102:17, :124:33]
        w_rprobeacklast = _RANDOM_2[12];	// @[MSHR.scala:102:17, :125:33]
        s_release = _RANDOM_2[13];	// @[MSHR.scala:102:17, :126:33]
        w_releaseack = _RANDOM_2[14];	// @[MSHR.scala:102:17, :127:33]
        s_pprobe = _RANDOM_2[15];	// @[MSHR.scala:102:17, :128:33]
        s_acquire = _RANDOM_2[16];	// @[MSHR.scala:102:17, :129:33]
        s_flush = _RANDOM_2[17];	// @[MSHR.scala:102:17, :130:33]
        w_grantfirst = _RANDOM_2[18];	// @[MSHR.scala:102:17, :131:33]
        w_grantlast = _RANDOM_2[19];	// @[MSHR.scala:102:17, :132:33]
        w_grant = _RANDOM_2[20];	// @[MSHR.scala:102:17, :133:33]
        w_pprobeackfirst = _RANDOM_2[21];	// @[MSHR.scala:102:17, :134:33]
        w_pprobeacklast = _RANDOM_2[22];	// @[MSHR.scala:102:17, :135:33]
        w_pprobeack = _RANDOM_2[23];	// @[MSHR.scala:102:17, :136:33]
        s_grantack = _RANDOM_2[25];	// @[MSHR.scala:102:17, :138:33]
        s_execute = _RANDOM_2[26];	// @[MSHR.scala:102:17, :139:33]
        w_grantack = _RANDOM_2[27];	// @[MSHR.scala:102:17, :140:33]
        s_writeback = _RANDOM_2[28];	// @[MSHR.scala:102:17, :141:33]
        sink = _RANDOM_2[31:29];	// @[MSHR.scala:102:17, :149:17]
        gotT = _RANDOM_3[0];	// @[MSHR.scala:150:17]
        bad_grant = _RANDOM_3[1];	// @[MSHR.scala:150:17, :151:22]
        probes_done = _RANDOM_3[2];	// @[MSHR.scala:150:17, :152:24]
        probes_toN = _RANDOM_3[3];	// @[MSHR.scala:150:17, :153:23]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign io_status_valid = request_valid;	// @[MSHR.scala:99:30]
  assign io_status_bits_set = request_set;	// @[MSHR.scala:100:20]
  assign io_status_bits_tag = request_tag;	// @[MSHR.scala:100:20]
  assign io_status_bits_way = meta_way;	// @[MSHR.scala:102:17]
  assign io_status_bits_blockC = ~meta_valid;	// @[MSHR.scala:101:27, :170:28]
  assign io_status_bits_nestC = _io_status_bits_nestC_output;	// @[MSHR.scala:175:39]
  assign io_schedule_valid = _io_schedule_valid_output;	// @[MSHR.scala:195:105]
  assign io_schedule_bits_a_valid = _io_schedule_bits_a_valid_output;	// @[MSHR.scala:186:55]
  assign io_schedule_bits_a_bits_tag = request_tag;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_a_bits_set = request_set;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_a_bits_param = {1'h0, req_needT ? (meta_hit ? 2'h2 : 2'h1) : 2'h0};	// @[MSHR.scala:99:30, :102:17, :106:22, :110:22, :113:22, :292:{35,41,56}, Parameters.scala:269:70]
  assign io_schedule_bits_a_bits_block = request_size != 3'h6 | ~(request_opcode == 3'h0 | (&request_opcode));	// @[MSHR.scala:100:20, :293:{51,91}, :294:{38,55,71}, Parameters.scala:270:{14,52,89}]
  assign io_schedule_bits_b_valid = _io_schedule_bits_b_valid_output;	// @[MSHR.scala:187:41]
  assign io_schedule_bits_b_bits_param = s_rprobe ? (request_prio_1 ? request_param : {1'h0, req_needT ? 2'h2 : 2'h1}) : 3'h2;	// @[MSHR.scala:99:30, :100:20, :110:22, :113:22, :123:33, :296:{41,61,97}, Parameters.scala:269:70, :281:43]
  assign io_schedule_bits_b_bits_tag = s_rprobe ? request_tag : meta_tag;	// @[MSHR.scala:100:20, :102:17, :123:33, :297:41]
  assign io_schedule_bits_b_bits_set = request_set;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_b_bits_clients = meta_clients & ~excluded_client;	// @[MSHR.scala:102:17, :289:28, :299:{51,53}]
  assign io_schedule_bits_b_bits_hit = io_directory_bits_hit;
  assign io_schedule_bits_c_valid = _io_schedule_bits_c_valid_output;	// @[MSHR.scala:188:43]
  assign io_schedule_bits_c_bits_opcode = {2'h3, meta_dirty};	// @[MSHR.scala:102:17, :117:22, :300:41]
  assign io_schedule_bits_c_bits_param = meta_state == 2'h1 ? 3'h2 : 3'h1;	// @[MSHR.scala:102:17, :110:22, :301:{41,53}, Parameters.scala:281:{11,43}]
  assign io_schedule_bits_c_bits_tag = meta_tag;	// @[MSHR.scala:102:17]
  assign io_schedule_bits_c_bits_set = request_set;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_c_bits_way = meta_way;	// @[MSHR.scala:102:17]
  assign io_schedule_bits_c_bits_dirty = meta_dirty;	// @[MSHR.scala:102:17]
  assign io_schedule_bits_d_valid = _io_schedule_bits_d_valid_output;	// @[MSHR.scala:189:57]
  assign io_schedule_bits_d_bits_prio_0 = request_prio_0;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_d_bits_prio_2 = request_prio_2;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_d_bits_opcode = request_opcode;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_d_bits_param = req_acquire ? (request_param == 3'h1 ? 3'h1 : request_param == 3'h2 ? {1'h0, meta_hit & meta_clients & req_clientBit ? 2'h2 : 2'h1} : request_param == 3'h0 ? {2'h0, req_acquire & (meta_hit ? ~meta_clients & (&meta_state) : gotT)} : request_param) : request_param;	// @[MSHR.scala:99:30, :100:20, :102:17, :106:22, :110:22, :113:22, :150:17, :229:53, :230:25, :231:{34,40,67,81}, :286:30, :308:41, :311:53, Mux.scala:81:{58,61}, Parameters.scala:46:9, :270:89, :281:{11,43}]
  assign io_schedule_bits_d_bits_size = request_size;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_d_bits_source = request_source;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_d_bits_offset = request_offset;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_d_bits_put = request_put;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_d_bits_set = request_set;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_d_bits_way = meta_way;	// @[MSHR.scala:102:17]
  assign io_schedule_bits_d_bits_bad = bad_grant;	// @[MSHR.scala:151:22]
  assign io_schedule_bits_d_bits_hit = io_directory_bits_hit;
  assign io_schedule_bits_e_valid = _io_schedule_bits_e_valid_output;	// @[MSHR.scala:190:43]
  assign io_schedule_bits_e_bits_sink = sink;	// @[MSHR.scala:149:17]
  assign io_schedule_bits_x_valid = _io_schedule_bits_x_valid_output;	// @[MSHR.scala:191:40]
  assign io_schedule_bits_dir_valid = _io_schedule_bits_dir_valid_output;	// @[MSHR.scala:192:66]
  assign io_schedule_bits_dir_bits_set = request_set;	// @[MSHR.scala:100:20]
  assign io_schedule_bits_dir_bits_way = meta_way;	// @[MSHR.scala:102:17]
  assign io_schedule_bits_dir_bits_data_dirty = s_release & _io_schedule_bits_dir_bits_data_WIRE_dirty;	// @[MSHR.scala:126:33, :233:52, :261:20, :262:21, :320:41]
  assign io_schedule_bits_dir_bits_data_state = s_release ? _io_schedule_bits_dir_bits_data_WIRE_state : 2'h0;	// @[MSHR.scala:106:22, :126:33, :233:52, :261:20, :262:21, :320:41]
  assign io_schedule_bits_dir_bits_data_clients = s_release & _io_schedule_bits_dir_bits_data_WIRE_clients;	// @[MSHR.scala:126:33, :233:52, :261:20, :262:21, :320:41]
  assign io_schedule_bits_dir_bits_data_tag = s_release ? (_GEN_0 ? meta_tag : request_tag) : 12'h0;	// @[MSHR.scala:100:20, :102:17, :126:33, :225:38, :233:52, :238:53, :257:30, :282:19, :320:41]
  assign io_schedule_bits_reload = no_wait;	// @[MSHR.scala:185:83]
endmodule

